mongodb_host: mongodb-{{ env }}.sitaram.icu
redis_host: redis-{{ env }}.sitaram.icu
rabbitmq_host: bitmqrab-{{ env }}.sitaram.icu
mysql_host: mysql-{{ env }}.sitaram.icu
catalogue_host: catalogue-{{ env }}.sitaram.icu
cart_host: cart-{{ env }}.sitaram.icu
user_host: user-{{ env }}.sitaram.icu
payment_host: payment-{{ env }}.sitaram.icu
shipping_host: shipping-{{ env }}.sitaram.icu
frontend_host: frontend-{{ env }}.sitaram.icu
frontend_host: sitaram.icu